# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Out
        uses: actions/checkout@v2
        
      - name: rsync deployments
        uses: contention/rsync-deployments@v1.0.0
        env:
          DEPLOY_KEY: ${{ secrets.ALIYUN_KEY }}
        with:
          args: "-avzr --delete --include public/ --exclude /* ${{ secrets.ALIYUN_USER }}@${{ secrets.ALIYUN_HOST }}:${{ secrets.ALIYUN_PATH }}"
        
#       - name: SCP Files to aliyun
#         uses: appleboy/scp-action@v0.1.1
#         with:
#           host: ${{ secrets.ALIYUN_HOST }}
#           username: ${{ secrets.ALIYUN_USER }}
#           password: ${{ secrets.ALIYUN_PASSWORD }}
#           source: "./public"
#           target: ${{ secrets.ALIYUN_PATH }}
          
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USER }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          script: bash /root/blog_develop.sh
          
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install automic-algolia
        run: | 
          npm install atomic-algolia
          npm run algolia
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
          ALGOLIA_INDEX_FILE: "./public/index.json"
